#! /bin/bash
# TAT unit test for the Property Recorded prologue
# Author: Igor Oya
# mail: igor.oya.vallejo@desy.de


echo " ******************  PropertyRecorderTATEpilogue ************* "
export ACS_CDB=$PWD/test_util
export ACS_TMP=$PWD/tmp
acsutilTATEpilogue
acscontainerdaemonStop
